#!/usr/bin/env python
# @author Stefano Borini - using bazaar now

import os; import sys; script_path=sys.path[0]; sys.path.append(os.path.join(script_path, "..")); 
import unittest

from IO import TestFileReader
from Utils import TestPeriodicTable
from Utils import Testzmatmodule
from FileParsers.Dalton import TestTokenizer
from FileParsers.Dalton import TestTokens
from InputGenerators.Dalton20 import TestMolFile

all_test_suite=unittest.TestSuite()

for test_case_class in [
                TestFileReader.TestFileReader,
                TestPeriodicTable.TestPeriodicTable,
                Testzmatmodule.Testzmatmodule,
                TestTokenizer.TestTokenizer,
                TestTokens.TestTokens,
                TestMolFile.TestMolFile,
                ]:
    all_test_suite.addTest(unittest.TestLoader().loadTestsFromTestCase(test_case_class))

unittest.TextTestRunner().run(all_test_suite)


    

