#/usr/bin/env python
# @author Stefano Borini
# @license Artistic License 2.0

import getopt
import os
import sys

def _usage():
    print "Usage : "+os.path.basename(sys.argv[0])
    print ""
    print "Computes the dipole for a given dalton file"
    print ""

opts, args=getopt.getopt(sys.argv[1:], "h", ["help"])

for opt in opts:
    if opt[0] == "-h" or opt[0] == "--help":
        _usage()
        sys.exit(1)

if len(args) < 1:
    _usage()
    sys.exit(1)

dalton_mol_filename = args[0]

f = file(os.path.join(os.getcwd(),"run.dal"),"w")
f.write("""# this file autogenerated by computeDipole20090413-2.py
**DALTON
.RUN WAVE FUNCTIONS 
.RUN PROPERTIES
.DIRECT
**INTEGRALS
.DIPLEN
.NOSUP
*END OF HERMIT
**WAVE FUNCTIONS
.DFT
CAMB3LYP
*SCF INP
.THRESH
1.0D-7
.MAX DIIS ITERATIONS
 100
*ORBITAL INP
.AO DELETE
1.0D-2
**PROPERTIES
**END OF DALTON INPUT"""
)
f.close()

sys.exit(os.system("cnrun dalton-2 run "+os.path.splitext(dalton_mol_filename)[0]))

