DJANGO_VERSION=1.1.1
DJANGO_TARGET=$(BUILD_FLAGS_DIR)/django

django: $(DJANGO_TARGET)

$(DJANGO_TARGET): $(INIT_TARGET) $(DOWNLOAD_DIR)/$(DJANGO_PACKAGE)
	export PATH=$(RUNTIME_DIR)/bin:$$PATH PYTHONPATH=$(RUNTIME_DIR)/lib/python2.5/site-packages/; \
	$(RUNTIME_DIR)/bin/easy_install-2.5 --prefix=$(RUNTIME_DIR) django==$(DJANGO_VERSION)
	touch $(DJANGO_TARGET)


ALL_RUNTIME_TARGETS+=$(DJANGO_TARGET)
