QUANTITIES_VERSION=0.6.0
QUANTITIES_TARGET=$(BUILD_FLAGS_DIR)/quantities

quantities: $(QUANTITIES_TARGET)

$(QUANTITIES_TARGET): $(INIT_TARGET) $(DOWNLOAD_DIR)/$(QUANTITIES_PACKAGE)
	export PATH=$(RUNTIME_DIR)/bin:$$PATH PYTHONPATH=$(RUNTIME_DIR)/lib/python2.5/site-packages/; \
	$(RUNTIME_DIR)/bin/easy_install-2.5 --prefix=$(RUNTIME_DIR) quantities==$(QUANTITIES_VERSION)
	touch $(QUANTITIES_TARGET)


ALL_RUNTIME_TARGETS+=$(QUANTITIES_TARGET)
